Add functions for POST APIs
1000ch/node-speedcurve pull request #3
Opened 2016-07-11 01:50 UTC by 1000ch

2018-02-23 19:28 UTC, lewisf commented
is there anything i can do to help with fixing the tests up and merging this in?

2018-04-26 06:27 UTC, lewisf commented
@andrewdelprete i ended up forking one internally -- but happy to help out with one if you fork it

2018-04-26 06:57 UTC, 1000ch commented
@lewisf @andrewdelprete 
Sorry for delay, I can add methods for POST APIs, but cannot test continuously. So I didn't merge this PR. How do you think? Should I remove tests for POST APIs to add methods?

2018-04-26 12:53 UTC, andrewdelprete requested changes

2018-04-26 12:53 UTC, andrewdelprete commented on index.js
> +    return request.post(`${API_ENDPOINT}/notes`, options);
should be /deploys instead of /notes here

2018-04-26 12:54 UTC, andrewdelprete commented
Hey @1000ch, yeah I'm okay with it personally! It's such a simple wrapper. I've just copied the class to my project but would love to just be able to npm install.

2018-04-26 17:15 UTC, merged

2018-05-03 17:25 UTC, andrewdelprete commented
Thanks for this! @1000ch